AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - test/dummy_app/bin/*
    - test/dummy_app/db/schema.rb

Layout/LineLength:
  Max: 207

Metrics/BlockLength:
  Max: 47

Metrics/ClassLength:
  Max: 140

Style/DoubleNegation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6
