AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - test/dummy_app/bin/*
    - test/dummy_app/db/schema.rb

# Metrics/AbcSize:
#   Enabled: false

# Metrics/ClassLength:
#   Enabled: false

# Metrics/CyclomaticComplexity:
#   Enabled: false

Documentation:
  Enabled: false

# Metrics/MethodLength:
#   Max: 10

Metrics/LineLength:
  Max: 200

Style/NumericLiterals:
  MinDigits: 6

# Metrics/PerceivedComplexity:
#   Enabled: false
